### ISSUE TITLE
Default Template doesn't work with nested folders

### ISSUE THREAD

**Issue by JeppeKlitgaard** [Vinzent03/obsidian-hotkeys-for-templates#8] opened 2021-06-01 11:15 UTC
Hi @Vinzent03!

CC @Moonbase59

Thank you so much for adding support for default templates for specific folders!

I have noticed that it currently doesn't work with nested folders though, which is something I would find super useful.

## Expected Behaviour

Default templates work for nested folder structures.

- 'Deepest match' has priority (if both `/a/` and `/a/b/` have templates specified, use template for `/a/b/`

## Actual Behaviour

Does not work for nested folders.

My setup is:

![image](https://user-images.githubusercontent.com/1814611/120314283-5edb7880-c2db-11eb-994d-d8418c2ef3b2.png)

But the template is only activated for files that are in `/` directly, not in, for example `/Physics/`.

This is not just for defining templates in `/` though. I have a template set for `/Physics/` as well in order to try to alleviate this, but `/Phyiscs/Quantum/newfile.md` will not make use of the `/Physics/` template.

**Comment by Vinzent03** [comment] 2021-06-01 13:18
I can confirm that applying a template for the root folder does not work for subfolders, but templates for any other folder works in my testing with subfolders.

**Comment by JeppeKlitgaard** [comment] 2021-06-01 13:46
🤦‍♂️ You're right. I was in my Math folder.

I could've sworn I couldn't get this to work the other day...

Nonetheless, support for a default specified on `/` would be super neat for those of us who have a lot of subfolders there as well!

**Comment by Vinzent03** [comment] 2021-06-01 13:48
Yeah I understand. It's because the root folder path is `/`, but the path of every subfolder is just `folder/subfolder` so without the `/`.  Will fix this.

**Comment by JeppeKlitgaard** [comment] 2021-06-01 13:53
I see.

Perfect, thank you so much. And thank you for making such a nice plugin - it is a real life-saver!

**Comment by Vinzent03** [comment] 2021-06-02 08:03
Should be fixed now!

**Closed** 2021-06-02 08:03 UTC
Labels: bug
