### ISSUE TITLE
Plugin Options blank on v0.12.12

### ISSUE THREAD

**Issue by PJJPtx** [Vinzent03/obsidian-hotkeys-for-templates#11] opened 2021-08-04 01:58 UTC
When I activate the plugin and go to Plugin Options, the page is blank with no fields, switches, or text of any kind. Could this be something with v0.12.12?

**Comment by Vinzent03** [comment] 2021-08-04 12:13
Is there any error in the console? (`CTRL + SHIFT + I`) And can you try to restart Obsidian?

**Comment by spudravi** [comment] 2021-08-09 03:22
seeing the same error, the error message on my console is 

`Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at te (app.js:1)
    at Module.ee (app.js:1)
    at HotkeysForTemplates.enumerateTemplates (eval at <anonymous> (app.js:1), <anonymous>:2269:51)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2170:35)
    at t.onLayoutReady (app.js:1)
    at HotkeysForTemplates.eval (eval at <anonymous> (app.js:1), <anonymous>:2168:44)
    at step (eval at <anonymous> (app.js:1), <anonymous>:68:23)
    at Object.eval [as next] (eval at <anonymous> (app.js:1), <anonymous>:49:53)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:39:58)`

and 

`Uncaught TypeError: Cannot read property 'replace' of undefined
    at te (app.js:1)
    at Module.ee (app.js:1)
    at HotkeysForTemplates.enumerateTemplates (eval at <anonymous> (app.js:1), <anonymous>:2269:51)
    at SettingsTab.display (eval at <anonymous> (app.js:1), <anonymous>:2508:21)
    at t.openTab (app.js:1)
    at HTMLDivElement.<anonymous> (app.js:1)`

**Comment by Vinzent03** [comment] 2021-08-16 11:07
So far I couldn't reproduce it. Did you install the plugin and then the issue appears, or have you already used it? Did something change that could cause this behavior?

**Comment by spudravi** [comment] 2021-08-16 11:53
Hey sorry, but it somehow fixed itself after i restarted obsidian 2 times

I dont know why it originally happened

**Comment by 1activegeek** [comment] 2021-11-02 18:12
I've run into this issue now as well. Not sure what is wrong here but it is erroring on the load with the following message:

```
app.js:1 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at Oe (app.js:1)
    at Module.Fe (app.js:1)
    at HotkeysForTemplates.enumerateTemplates (eval at <anonymous> (app.js:1), <anonymous>:2248:48)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2170:35)
    at t.onLayoutReady (app.js:1)
    at HotkeysForTemplates.eval (eval at <anonymous> (app.js:1), <anonymous>:2168:44)
    at step (eval at <anonymous> (app.js:1), <anonymous>:68:23)
    at Object.eval [as next] (eval at <anonymous> (app.js:1), <anonymous>:49:53)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:39:58)
```

**Comment by Vinzent03** [comment] 2021-11-02 18:21
@1activegeek Did you install the plugin just now or were you already using it?

**Comment by 1activegeek** [comment] 2021-11-02 18:43
Freshly installed. Though I also tried loading the old version first, then "updating" in the console of Obsidian. Also involved completely closing an restarting the app. None of those options resulted in success.

**Comment by Vinzent03** [comment] 2021-11-02 22:01
Ok after some researching I think you have the templater plugin enabled? There's something wrong with the templater folder. Could you try clearing the textfield and reentering the path? And if the issue still persists please share the output of the following command in the console (`Ctrl + Shift + I`) `app.plugins.plugins["templater-obsidian"].settings.templates_folder`

**Comment by 1activegeek** [comment] 2021-11-03 00:01
I can certainly give this a go. When you say clear the field - do you mean in the templater settings? Or in your plugin settings? If the later, that wouldn't be possible as nothing shows up in the settings window.

**Comment by 1activegeek** [comment] 2021-11-03 02:24
So I ran the command you mentioned first out of interest in the current working version of the plugin, the result was `undefined`. As you can see here, this is with your plugin working and it currently returns undefined:
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/6810720/140001897-a8e58381-e0b5-4e76-ad16-513f359a2740.png">
Fairly certain that is undesirable, so updating to the latest version is also likely to fail as your plugin won't change this setting on the templater plugin. I've also disabled the core templates plugin just in case there was competing issues.

**Comment by Vinzent03** [comment] 2021-11-03 08:32
Are you on template version < 1.9? If not, please update.

**Closed** 2021-11-05 14:40 UTC
